"use client";

import React, { useState } from "react";
import { FilmProject } from "@/data/film-intelligence-types";

interface StageViewProps {
  project: FilmProject;
  onUpdateProject: (updates: Partial<FilmProject>) => void;
  onNextStage?: () => void;
  onMarkComplete?: () => void;
  isCompleted?: boolean;
}

export function ArchiveStageView({
  project,
  onMarkComplete,
  isCompleted,
}: StageViewProps) {
  const [copied, setCopied] = useState(false);

  const scenes = project.scenes || [];
  const totalShots = scenes.reduce((acc, s) => acc + (s.shots?.length || 0), 0);

  const generateMarkdownDossier = () => {
    return `# DIRECTOR'S PROJECT DOSSIER: ${project.title.toUpperCase()}
Type: ${project.projectType || "Short Film"} | Est. Runtime: ${project.estimatedRuntimeMinutes || "N/A"} mins | Year: ${project.targetReleaseYear || "2026"}
Country: ${project.countryOfOrigin || "N/A"} | Genres: ${(project.genre || []).join(", ")}

## 1. LOGLINE & CREATIVE INTENT
**Logline:**
${project.logline || "No logline defined."}

**Creative Intent:**
${project.creativeIntent || "No statement of intent defined."}

**Synopsis:**
${project.synopsis || "No synopsis recorded."}

## 2. VISUAL LANGUAGE BIBLE
- Aspect Ratio: ${project.visualLanguage?.aspectRatio || "N/A"}
- Optics & Glass: ${project.visualLanguage?.opticsDescription || "N/A"}
- Lighting Ratio: ${project.visualLanguage?.lightingRatio || "N/A"}
- Camera Movement: ${project.visualLanguage?.cameraMovementPhilosophy || "N/A"}
- Texture & Grain: ${project.visualLanguage?.grainTexture || "N/A"}

### Color Palette:
${(project.visualLanguage?.colorPalette || [])
  .map((s) => (typeof s === "string" ? `- ${s}` : `- ${s.label} (${s.hex}): ${s.role}`))
  .join("\n")}

## 3. SCENE BREAKDOWN & SHOT COVERAGE (${scenes.length} Scenes, ${totalShots} Setups)
${scenes
  .map(
    (sc) => `### Scene ${sc.sceneNumber}: ${sc.slugline}
Location: ${sc.location} | Time: ${sc.timeOfDay} | Est. Duration: ${sc.estDurationSeconds}s
Dramatic Beat: ${sc.dramaticBeat}

Shots:
${(sc.shots || [])
  .map(
    (sh) =>
      `  - [${sh.shotNumber}] ${sh.framing} (${sh.focalLength}) | ${sh.cameraMovement} | Status: ${sh.status}\n    Action: ${sh.description}\n    Lighting: ${sh.lightingNote}`
  )
  .join("\n")}`
  )
  .join("\n\n")}

## 4. CONNECTED KNOWLEDGE GRAPH ENTITIES
- Linked Research IDs: ${(project.researchIds || []).join(", ") || "None"}
- Linked Technique IDs: ${(project.techniqueIds || []).join(", ") || "None"}
- Linked Tool IDs: ${(project.toolIds || []).join(", ") || "None"}
- Linked Prompt IDs: ${(project.promptIds || []).join(", ") || "None"}
- Target Festival IDs: ${(project.festivalIds || []).join(", ") || "None"}

---
Generated by Creator Intel Director's Toolkit.
`;
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdownDossier();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadJSON = () => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(project, null, 2));
    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `${project.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}-project-dossier.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Stage Header */}
      <div className="surface rounded-2xl border border-border p-6 space-y-2">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <span className="font-mono text-xs text-accent font-bold">STAGE 09</span>
            <span className="text-tertiary text-xs">•</span>
            <span className="text-xs font-mono text-secondary uppercase tracking-wider">Archival</span>
          </div>
          {onMarkComplete && (
            <button
              onClick={onMarkComplete}
              className={`rounded-lg px-3 py-1 text-xs font-mono font-semibold transition border cursor-pointer ${
                isCompleted
                  ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/20"
                  : "bg-surface-elevated border-border text-tertiary hover:text-primary hover:border-border-bright"
              }`}
            >
              {isCompleted ? "✓ Stage 09 Marked Complete" : "Mark Stage Complete"}
            </button>
          )}
        </div>
        <h1 className="text-2xl font-serif text-primary font-bold">Archive & Project Dossier Export</h1>
        <p className="text-sm text-secondary">
          Export your complete director's bible, technical shot breakdown, and festival package in standard production formats.
        </p>
      </div>

      {/* Export Actions */}
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
        <button
          onClick={handleCopyMarkdown}
          className="surface rounded-2xl border border-border p-5 text-left space-y-2 hover:border-accent cursor-pointer transition"
        >
          <span className="text-xl">📄</span>
          <h3 className="font-mono text-xs font-bold uppercase tracking-wider text-primary">
            {copied ? "✓ Copied to Clipboard" : "Copy Markdown Dossier"}
          </h3>
          <p className="text-[11px] text-secondary">
            Full production bible formatted in GitHub/Obsidian compatible Markdown.
          </p>
        </button>

        <button
          onClick={handleDownloadJSON}
          className="surface rounded-2xl border border-border p-5 text-left space-y-2 hover:border-accent cursor-pointer transition"
        >
          <span className="text-xl">💾</span>
          <h3 className="font-mono text-xs font-bold uppercase tracking-wider text-primary">
            Download JSON Package
          </h3>
          <p className="text-[11px] text-secondary">
            Machine-readable project schema with all relational IDs and shot setups.
          </p>
        </button>

        <button
          onClick={handlePrint}
          className="surface rounded-2xl border border-border p-5 text-left space-y-2 hover:border-accent cursor-pointer transition"
        >
          <span className="text-xl">🖨️</span>
          <h3 className="font-mono text-xs font-bold uppercase tracking-wider text-primary">
            Print / Save to PDF
          </h3>
          <p className="text-[11px] text-secondary">
            Print-ready layout for physical production binders and pitch meetings.
          </p>
        </button>
      </div>

      {/* Dossier Preview */}
      <div className="surface rounded-2xl border border-border p-6 space-y-4">
        <h2 className="text-sm font-semibold uppercase tracking-wider font-mono text-primary">
          Project Dossier Preview
        </h2>
        <pre className="rounded-xl border border-border bg-surface-elevated p-4 text-xs font-mono text-secondary overflow-x-auto max-h-96 leading-relaxed whitespace-pre-wrap">
          {generateMarkdownDossier()}
        </pre>
      </div>
    </div>
  );
}
