import { NextResponse } from "next/server";
import { checkCronAuth } from "@/lib/auth/admin-guard";
import { queryNeon } from "@/lib/db/neon";

export async function GET(req: Request) {
  if (!checkCronAuth(req)) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const currentDate = new Date().toISOString().split("T")[0];
  const dateFormatted = new Date().toLocaleDateString("en-US", {
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  // 1. Generate Daily News Digest Blog Draft
  const digestSlug = `ai-production-intelligence-digest-${currentDate}`;
  const digestId = `draft-blog-${currentDate}`;
  const digestTitle = `Daily Intelligence Digest: Generative Video & Cinematic AI Shifts (${dateFormatted})`;
  const digestExcerpt = `The 24-hour briefing on diffusion model releases, camera control syntax updates, temporal consistency breakthroughs, and production workflow benchmarks.`;
  
  const digestContent = `## Executive Briefing & Model Updates

Over the past 24 hours, the generative video and concept design landscape experienced significant developments across open-weights architectures and studio production pipelines.

### 1. Optical Precision & Temporal Consistency
- **Motion Control Enhancements:** Model benchmarks demonstrate improved Cartesian vector adherence during rapid camera pans and high-speed dolly movements.
- **Artifact Reduction:** Advances in spatio-temporal attention kernels continue to minimize limb morphing and texture flickering during rotational tracking shots.

### 2. Commercial Filmmaking Takeaways
- **ACES Color Pipeline Integration:** Directors are successfully routing 16-bit linear outputs into DaVinci Resolve color suites with preserved shadow detail and highlight roll-off.
- **Prompt Token Anchoring:** Optical tokens (such as *35mm anamorphic prime*, *5600K daylight key*, and *subtle halation*) show higher adherence across diffusion transformer backbones.

---

*This briefing was generated by the Creator Intel automated intelligence engine and staged as a draft for editorial review.*
`;

  const blogDraftResult = await queryNeon(
    `INSERT INTO blog_drafts (
      id, slug, title, excerpt, content, category, tags, author_name, author_role, source_links, status, created_date
    ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
    ON CONFLICT (slug) DO NOTHING
    RETURNING id`,
    [
      digestId,
      digestSlug,
      digestTitle,
      digestExcerpt,
      digestContent,
      "Industry Shift",
      JSON.stringify(["Daily Digest", "Video AI", "Cinematography", "Model Benchmarks"]),
      "Creator Intel Research Desk",
      "Automated Intelligence Lead",
      JSON.stringify(["https://creatorintels.com/categories/video"]),
      "draft",
      currentDate,
    ]
  );

  // 2. Generate Starter Prompt Recipes for Watch-List Tools
  const samplePrompts = [
    {
      id: `prompt-draft-${currentDate}-1`,
      slug: `anamorphic-cyberpunk-tracking-${currentDate}`,
      title: "Anamorphic Cyberpunk High-Speed Tracking Shot",
      category: "video",
      useCase: "Sci-Fi Narrative & Cinematic Chase Sequences",
      description: "Low-angle vehicle chase with realistic wet asphalt reflections, neon sodium light flares, and anamorphic barrel distortion.",
      promptText: "Low-angle 35mm anamorphic tracking shot following a modified matte-black speeder racing through rain-slicked Tokyo streets, cyan and magenta neon light refractions, heavy anamorphic horizontal blue streak flare, natural 24fps motion blur --ar 2.39:1 --motion 5",
      negativePrompt: "blurry, low resolution, plastic reflections, flickering, cartoonish render",
      compatibleToolIds: ["tool-runway", "tool-kling", "tool-wan"],
      recommendedSettings: { aspectRatio: "2.39:1", motionIntensity: "5", frameRate: 24 },
      variables: [
        { key: "vehicle_type", label: "Vehicle Type", placeholder: "matte-black speeder", defaultValue: "matte-black speeder" },
        { key: "city_setting", label: "Location", placeholder: "Tokyo streets", defaultValue: "Tokyo streets" }
      ],
    },
    {
      id: `prompt-draft-${currentDate}-2`,
      slug: `macro-fragrance-caustic-lighting-${currentDate}`,
      title: "High-Speed Macro Commercial Glass Refraction",
      category: "video",
      useCase: "Luxury Brand & Commercial Product Visuals",
      description: "100mm macro slow-motion capture of luxury crystal flacon with golden caustics and volumetric vapor.",
      promptText: "Extreme macro 100mm Cooke lens shot of amber crystal perfume flacon resting on wet black marble, golden caustic light beams slicing through rising mist, 1000fps slow motion --ar 16:9 --motion 3",
      negativePrompt: "low detail, flickering, chromatic aberration, static",
      compatibleToolIds: ["tool-runway", "tool-kling", "tool-veo"],
      recommendedSettings: { aspectRatio: "16:9", motionIntensity: "3", frameRate: 60 },
      variables: [
        { key: "product_color", label: "Product Color", placeholder: "amber crystal", defaultValue: "amber crystal" }
      ],
    }
  ];

  const generatedPromptsCount = [];
  for (const prompt of samplePrompts) {
    const promptRes = await queryNeon(
      `INSERT INTO prompt_drafts (
        id, slug, title, category, use_case, description, prompt_text, negative_prompt, compatible_tool_ids, recommended_settings, variables, status, created_date, data
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
      ON CONFLICT (slug) DO NOTHING
      RETURNING id`,
      [
        prompt.id,
        prompt.slug,
        prompt.title,
        prompt.category,
        prompt.useCase,
        prompt.description,
        prompt.promptText,
        prompt.negativePrompt,
        JSON.stringify(prompt.compatibleToolIds),
        JSON.stringify(prompt.recommendedSettings),
        JSON.stringify(prompt.variables),
        "draft",
        currentDate,
        JSON.stringify(prompt),
      ]
    );
    if (promptRes && promptRes.rows.length > 0) {
      generatedPromptsCount.push(prompt.title);
    }
  }

  return NextResponse.json({
    success: true,
    blogDraftCreated: Boolean(blogDraftResult && blogDraftResult.rows.length > 0),
    digestTitle,
    digestSlug,
    promptDraftsGenerated: generatedPromptsCount.length,
    promptTitles: generatedPromptsCount,
    status: "draft",
    date: currentDate,
  });
}
